<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <Version>0.0.0.0</Version>
        <LangVersion>preview</LangVersion>
        <Author>Jukkales</Author>
        <Name>HoardFarm</Name>
        <InternalName>HoardFarm</InternalName>
        <Punchline>Become an accursed Hoarder!</Punchline>
        <Description>Plugin to help farming DeepDungeon Hoards (...for you)</Description>
        <RepoUrl>https://github.com/Jukkales/HoardFarm</RepoUrl>
        <IconUrl>https://github.com/Jukkales/HoardFarm/raw/main/icon.png</IconUrl>
        <Tags>hoard;farm;help;achievement;hoarder;accursed</Tags>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ECommons" Version="3.2.1.15" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AutoRetainerAPI\AutoRetainerAPI\AutoRetainerAPI.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Data\Strings.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Strings.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Data\Strings.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Strings.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
